AgendaBundle\Entity\Events:
    type: entity
    table: events
    repositoryClass: AgendaBundle\Entity\EventsRepository
    indexes:
        event_user:
            columns:
                - id_user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        start:
            type: datetime
            nullable: false
        end:
            type: datetime
            nullable: false
        titre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        contenu:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        backgroundColor:
            type: string
    manyToOne:
        idUser:
            targetEntity: UserBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
