<?php
namespace GedBundle\Entity;
/**
 * DocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByOld()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('d')
            ->from($this->_entityName, 'd')// Dans un repository, $this->_entityName est le namespace de l'entité gérée
            ->Where('d.finDeVie <= :now')
            ->setParameter('now', new \DateTime('now'));
        return $queryBuilder->getQuery()->getResult();
    }

    // Permet de compter le nombre de document présent dans la GED
    public function getNbDocuments() {

        return $this->createQueryBuilder('id')
            ->select('COUNT(id)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    // Permet de compter le nombre de document uploader durant le dernier mois
    public function getNbDocumentsMonth()
    {
        return $this->createQueryBuilder('id')
            ->select('COUNT(id)')
            ->where('id.dateAjout > :create_at')
            ->setParameter('create_at', date('Y-m-d', time() - 86400 * 30) )
            ->getQuery()
            ->getSingleScalarResult();
    }
}