<?php

namespace FormBundle\Entity;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationsRepository extends \Doctrine\ORM\EntityRepository
{
    /* public function findByIdRecipient($id_recipient)
     {
         // Selection par ID recipient trier par date
         return $this->getEntityManager()
             ->createQuery(
                 'SELECT p FROM MsgBundle:Message p WHERE p.id_recipient = :recipient ORDER BY p.date ASC'
             )->setParameter('recipient', $id_recipient)
             ->getResult();
     }*/

    public function findByNom($nom)
    {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Organisme p WHERE p.nom = :name'
            )->setParameter('name', $nom)
            ->getResult();
    }

}
