#!/bin/bash
message=`pwd`

echo "\033[31;1;4;5;7mChangement de la branche\033[0m\n"
sudo git checkout develop
echo "Appuyer sur Entrée pour continuer..."
read a


echo "\033[31;1;4;5;7mLancement du composer install\033[0m\n"
sudo composer install
echo "Appuyer sur Entrée pour continuer..."
read a
clear


echo "\033[31;1;4;5;7mCreation de la database\033[0m\n"
sudo php app/console doctrine:database:create
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mUpdate de la database\033[0m\n"
sudo php app/console doctrine:schema:update --force
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mInsertion des fixtures\033[0m\n"
sudo php app/console doctrine:fixtures:load
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mDroits en ecriture\033[0m\n"
sudo sh bash/chmod.sh
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mCréation de upload\033[0m\n"
cd app/
echo "\033[34mVous êtes dans le dossier $message\033[0m"
echo "Appuyer sur Entrée pour continuer..."
read a
clear

sudo mkdir uploads
cd uploads/
echo "\033[34mVous êtes dans le dossier $message\033[0m"
echo "Appuyer sur Entrée pour continuer..."
read a
clear

sudo mkidr documents
cd ..
echo "\033[34mVous êtes dans le dossier $message\033[0m"
echo "Appuyer sur Entrée pour continuer..."
read a
clear

cd ..
echo "\033[34mVous êtes dans le dossier $message\033[0m"
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mInstallation de Grunt\033[0m\n"
sudo npm install
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mLancement de Grunt\033[0m\n"
sudo grunt
