#!/bin/bash
message=`pwd`

echo "\033[31;1;4;5;7mChangement de la branche\033[0m\n"
sudo git checkout develop

echo "\033[31;1;4;5;7mLancement du composer install\033[0m\n"
sudo composer install

echo "\033[31;1;4;5;7mCreation de la database\033[0m\n"
sudo php app/console doctrine:database:create

echo "\033[31;1;4;5;7mUpdate de la database\033[0m\n"
sudo php app/console doctrine:schema:update --force

echo "\033[31;1;4;5;7mInsertion des fixtures\033[0m\n"
sudo php app/console doctrine:fixtures:load

echo "\033[31;1;4;5;7mDroits en ecriture\033[0m\n"
sudo sh bash/chmod.sh

echo "\033[31;1;4;5;7mCréation de upload\033[0m\n"
cd app/
echo "\033[34mVous êtes dans le dossier $message\033[0m"
sudo mkdir uploads
cd uploads/
echo "\033[34mVous êtes dans le dossier $message\033[0m"
sudo mkidr documents
cd ..
echo "\033[34mVous êtes dans le dossier $message\033[0m"
cd ..
echo "\033[34mVous êtes dans le dossier $message\033[0m"

echo "\033[31;1;4;5;7mInstallation de Grunt\033[0m\n"
sudo npm install

echo "\033[31;1;4;5;7mLancement de Grunt\033[0m\n"
sudo grunt
