#!/bin/bash

echo "\033[31;1;4;5;7mVérification de composer\033[0m\n"

if [ ! -d "/usr/local/bin/composer" ];then
	echo "\033[31;1;4;5;7mInstallation de composer en global\033[0m\n"
	curl -sS https://getcomposer.org/installer | php
	sudo mv composer.phar /usr/local/bin/composer
fi
echo "Composer est déjà installé"
read a
clear


echo "\033[31;1;4;5;7mChangement de la branche\033[0m\n"
sudo git checkout develop
echo "Appuyer sur Entrée pour continuer..."
read a
clear


echo "\033[31;1;4;5;7mLancement du composer install\033[0m\n"
sudo composer install
echo "Appuyer sur Entrée pour continuer..."
read a
clear


echo "\033[31;1;4;5;7mCreation de la database\033[0m\n"
sudo php app/console doctrine:database:create
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mUpdate de la database\033[0m\n"
sudo php app/console doctrine:schema:update --force
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mInsertion des fixtures\033[0m\n"
sudo php app/console doctrine:fixtures:load
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mDroits en ecriture\033[0m\n"
pwd
sudo sh bash/chmod.sh
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mCréation de upload\033[0m\n"
cd app/
pwd
sudo mkdir uploads
cd uploads/
pwd
sudo mkdir documents
cd ..
pwd
cd ..
pwd
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mVérification de NodeJS\033[0m\n"

if [ ! -d "/usr/local/bin/grunt" ];then
	sudo apt-get update
	sudo apt-get install nodejs npm
	echo "\033[31;1;4;5;7mInstallation de Grunt en global\033[0m\n"
	sudo npm install -g grunt-cli
fi
echo "Grunt est déjà installé"
read a
clear

echo "\033[31;1;4;5;7mInstallation de Grunt\033[0m\n"
sudo npm install
echo "Appuyer sur Entrée pour continuer..."
read a
clear

echo "\033[31;1;4;5;7mLancement de Grunt\033[0m\n"
sudo grunt
