MsgBundle\Entity\Message:
    type: entity
    table: null
    repositoryClass: MsgBundle\Entity\MessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        recipient:
            type: string
            length: 255
        sender:
            type: string
            length: 255
        sender_name:
            type: string
            length: 255
        visible_in_box_receiver:
            type: boolean
        subject:
            type: string
            length: 255
        message:
            type: text
        date:
            type: datetime
    lifecycleCallbacks: {  }
