offres_offres-emploi_:
    resource: "@OffresBundle/Resources/config/routing/offres.yml"
    prefix:   /offres-emploi/

offres_homepage:
    path:     /hello/{name}
    defaults: { _controller: OffresBundle:Default:index }

organisme_get_picture:
    path:      /organisme/{picture}
    defaults: { _controller: "AppBundle:Organisme:PictureOrganisme" }
    methods: [GET]