homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

# Route bundle AnnuaireBundle
annuaire:
    resource: "@AnnuaireBundle/Resources/config/routing.yml"
    prefix:   /annuaire

# Route bundle MsgBundle
msg:
    resource: "@MsgBundle/Resources/config/routing.yml"
    prefix:   /message

# Route bundle AgendaBundle
agenda:
    resource: "@AgendaBundle/Resources/config/routing.yml"
    prefix:   /agenda

# Route bundle GedBundle
ged_documents:
    resource: "@GedBundle/Resources/config/routing.yml"
    prefix:   /documents

# Route bundle FosUserBundle && UserBundle
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /profile

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /profile

# Route bundle AppBundle
admin:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /admin

user_validation:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

# Permet de renvoyer un click sur js vers une route
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"