# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: UserBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }

    app.actu:
        class: ActuBundle\Service\ActuService
        arguments:
            - @doctrine.orm.default_entity_manager