<?php

namespace UserBundle\Entity;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * StatistiquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiquesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbConnectionParJour()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('COUNT(s)')
            ->from($this->_entityName, 's')// Dans un repository, $this->_entityName est le namespace de l'entité gérée
            ->Where('s.date <= :now')
            ->setParameter('now', new \Datetime());
        return $queryBuilder->getQuery()->getSingleScalarResult();
    }

    public function getNbConnectionParMois()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('COUNT(s)')
            ->from($this->_entityName, 's')// Dans un repository, $this->_entityName est le namespace de l'entité gérée
            ->Where('s.date BETWEEN :mois AND :auj')
            ->setParameter('mois', 'convert(datetime,SUBSTRING(CONVERT(varchar(8), GETDATE(), 112), 1, 6) + \'01\')')
            ->setParameter('auj', new \DateTime('now'));
        return $queryBuilder->getQuery()->getSingleScalarResult();
    }

    public function getStatistiquesParMois()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('SUBSTRING(s.date, 1, 7) as month, SUM(s.nbVisitesAccueil) as visites')
            ->from($this->_entityName, 's')// Dans un repository, $this->_entityName est le namespace de l'entité gérée
            ->groupBy('month');
        $result = $queryBuilder->getQuery()->getResult();
        return $result;
    }
}