<?php

namespace UserBundle\Entity;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUsername($username)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM UserBundle:User p WHERE p.username = :name ORDER BY p.date ASC'
            )->setParameter('name', $username)
            ->getResult();
    }
}