<?php
namespace AgendaBundle\Entity;
/**
 * DocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByOld()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('e')
            ->from($this->_entityName, 'e')// Dans un repository, $this->_entityName est le namespace de l'entité gérée
            ->Where('e.start <= :old')
            ->setParameter('old', date('Y-m-d', time() - 3600 * 24 *30 * 5)); // date now moin 5 mois
        return $queryBuilder->getQuery()->getResult();
    }
}