dashboard:
    path:     /
    defaults: { _controller: "AppBundle:Default:admin" }
    options:
        expose: true

admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix:   /

