<?php

namespace AppBundle\Entity;

/**
 * OrganismeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismeRepository extends \Doctrine\ORM\EntityRepository
{
}
